Repository hmcts/ccd-data-store-api, pull requests merged in 2018-04, with the labels that each got.

#5 Attempt to fix build.
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/CreatorSearchOperationTest.java
Labels: bug

#7 RDM-1992 reverted to old mockito …
  build.gradle
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/CreatorSearchOperationTest.java
Labels: bug

#8 RDM-1448: Enforce user access at DB level
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CachedCaseDetailsRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilderFactory.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/CountCaseDetailsQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/SelectCaseDetailsQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/UserAuthorisationSecurity.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/SearchQueryFactoryOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessService.java
  src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisation.java
  src/main/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfiguration.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/CachedCaseDetailsRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/query/CaseDetailsQueryBuilderFactoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/query/UserAuthorisationSecurityTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/SQLBuilderForSearchTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpointIT.java
  src/test/java/uk/gov/hmcts/ccd/infrastructure/user/UserAuthorisationConfigurationTest.java
  src/test/resources/sql/insert_case_users.sql
  src/test/resources/sql/insert_cases.sql
Labels: enhancement

#24 RDM-2013 Do not override case data's default classification on each e…
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/FieldType.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataService.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationUtils.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/DefaultCreateCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/DefaultCreateEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/stdapi/CallbackInvoker.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlTestUtil.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseDataServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/CallbackInvokerTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
  src/test/resources/sql/insert_cases.sql
Labels: checkpoint
