Repository hmcts/ccd-data-store-api, pull requests merged in 2018-09, with the labels that each got.

#158 Rdm 2222 As a user I want to submit my draft form
  src/main/java/uk/gov/hmcts/ccd/data/draft/DefaultDraftGateway.java
  src/main/java/uk/gov/hmcts/ccd/data/draft/DraftGateway.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/std/CaseDataContent.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/AuthorisedCreateCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/ClassifiedCreateCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/CreateCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/DefaultCreateCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
  src/test/java/uk/gov/hmcts/ccd/data/draft/DefaultDraftGatewayTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/AuthorisedCreateCaseOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/ClassifiedCreateCaseOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/DefaultCreateCaseOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/DefaultCreateEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointIT.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointTest.java
  src/test/resources/mappings/delete-draft.json
Labels: checkpoint

#180 Rdm 1626
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/JurisdictionMapper.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseTypeDisplayProperties.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/JurisdictionDisplayProperties.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/Jurisdiction.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/JurisdictionMapperTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseTypesOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
Labels: enhancement

#178 [PREVIEW] RDM-2736: API v2: Get Case by reference
  build.gradle
  lombok.config
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/BaseTest.java
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/v2/external/GetCaseTest.java
  src/main/java/uk/gov/hmcts/ccd/CoreCaseDataApplication.java
  src/main/java/uk/gov/hmcts/ccd/config/JacksonObjectMapperConfig.java
  src/main/java/uk/gov/hmcts/ccd/v2/V2.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseController.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/resource/CaseResource.java
  src/test/java/uk/gov/hmcts/ccd/config/JacksonObjectMapperConfigTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/resource/CaseResourceTest.java
Labels: checkpoint

#209 RDM-2736: Fix Sonar quality on path to live
  src/main/java/uk/gov/hmcts/ccd/config/JacksonObjectMapperConfig.java
  src/main/java/uk/gov/hmcts/ccd/v2/V2.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseController.java
Labels: bug
