Repository hmcts/ccd-data-store-api, pull requests merged in 2018-11, with the labels that each got.

#235 RDM-2840 Get Case by API
  README.md
  src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
  src/main/java/uk/gov/hmcts/ccd/config/HalConfig.java
  src/main/java/uk/gov/hmcts/ccd/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/data/caseaccess/CachedCaseRoleRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/caseaccess/CaseRoleRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/caseaccess/CaseUserEntity.java
  src/main/java/uk/gov/hmcts/ccd/data/caseaccess/CaseUserRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/caseaccess/DefaultCaseRoleRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsEntity.java
  src/main/java/uk/gov/hmcts/ccd/data/user/CachedUserRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/user/UserRepository.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/UserDefault.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseRole.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AbstractAuthorisedCaseViewOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseHistoryViewOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseViewOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseTypeService.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/getcase/AuthorisedGetCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/mapper/CaseDetailsMapper.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpoint.java
  src/test/java/uk/gov/hmcts/ccd/config/HalConfigTest.java
  src/test/java/uk/gov/hmcts/ccd/config/JacksonObjectMapperConfigTest.java
  src/test/java/uk/gov/hmcts/ccd/data/caseaccess/CachedCaseRoleRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/caseaccess/CaseUserRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/caseaccess/DefaultCaseRoleRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/CachedCaseDetailsRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/user/CachedUserRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseHistoryViewOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseViewOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseTypeServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/DefaultAuthorisedCaseDefinitionDataServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/getcase/AuthorisedGetCaseOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/getcase/DefaultGetCaseOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/security/AuthorisedCaseSearchOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CallbackTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpointIT.java
Labels: enhancement

#256 RDM-3288 Implement external Start new case endpoint in API v2
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/v2/external/GetStartTriggerTest.java
  src/main/java/uk/gov/hmcts/ccd/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/callbacks/StartEventTrigger.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseType.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/StartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/v2/V2.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerController.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/resource/StartTriggerResource.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/resource/StartTriggerResourceTest.java
Labels: enhancement

#261 RDM-3289 Implement internal Start new case endpoint in API v2
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/v2/external/GetStartTriggerTest.java
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/v2/internal/GetUIStartTriggerTest.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/GetEventTriggerOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/StartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
  src/main/java/uk/gov/hmcts/ccd/v2/V2.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerController.java
  src/main/java/uk/gov/hmcts/ccd/v2/internal/controller/UIStartTriggerController.java
  src/main/java/uk/gov/hmcts/ccd/v2/internal/resource/UIStartTriggerResource.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/GetEventTriggerOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceFilterTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/resource/StartTriggerResourceTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UIStartTriggerControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/internal/resource/UIStartTriggerResourceTest.java
Labels: enhancement

#266 RDM-3289 Fix a test that was broken by uploading new def store CCD_CN…
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/v2/internal/GetUIStartTriggerTest.java
Labels: bug

#268 Rdm 3447 Implement external Start new event endpoint in API v2
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/v2/external/GetStartTriggerTest.java
  src/main/java/uk/gov/hmcts/ccd/CachingConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CachedCaseDetailsRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/DefaultCaseDetailsRepository.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/callbacks/StartEventTrigger.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/GetEventTriggerOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/startevent/StartEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpoint.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/ui/QueryEndpoint.java
  src/main/java/uk/gov/hmcts/ccd/v2/V2.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerController.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/resource/StartTriggerResource.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetEventTriggerOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/DefaultGetEventTriggerOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/GetEventTriggerOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/AuthorisedStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/ClassifiedStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/startevent/DefaultStartEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/ui/CallbackTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/StartTriggerControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/resource/StartTriggerResourceTest.java
Labels: checkpoint
