Repository hmcts/ccd-data-store-api, pull requests merged in 2018-06, with the labels that each got.

#98 fix for functional tests & sIdam Integration
  src/aat/java/uk/gov/hmcts/ccd/datastore/tests/helper/idam/IdamApi.java
Labels: bug

#65 RDM-1149 DateTime Support
  src/main/java/uk/gov/hmcts/ccd/domain/types/DateTimeValidator.java
  src/test/java/uk/gov/hmcts/ccd/TestConfiguration.java
  src/test/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepositoryIT.java
  src/test/java/uk/gov/hmcts/ccd/domain/types/DateTimeValidatorTest.java
  src/test/resources/mappings/base-types.json
Labels: enhancement

#74 RDM-2258 Update docs for OrderSummary predefined complex type.
  docs/api/case-data.md
Labels: checkpoint
