Repository hmcts/ccd-data-store-api, pull requests merged in 2020-12, with the labels that each got.

#1225 RDM-10165: Update V2 createEvent API
  dependency-check-suppressions.xml
  src/aat/resources/features/F-027/S-038_ANY.td.json
  src/aat/resources/features/F-027/S-038_Full.td.json
  src/aat/resources/features/F-027/S-590.td.json
  src/aat/resources/features/F-067/S-212.td.json
  src/aat/resources/features/F-067/S-212_Get_Case_Data.td.json
  src/aat/resources/features/F-126/F-126.feature
  src/aat/resources/features/F-126/F126_Case_Data_Create.td.json
  src/aat/resources/features/F-126/F126_Case_Data_Create_C1.td.json
  src/aat/resources/features/F-126/F126_Case_Data_Create_C1_Token_Creation.td.json
  src/aat/resources/features/F-126/F126_Case_Data_Create_Token_Creation.td.json
  src/aat/resources/features/F-126/F126_Get_CaseEvent_With_On_Behalf_Of_User.td.json
  src/aat/resources/features/F-126/F126_Prerequisite_Citizen_Token_For_Update_Case.td.json
  src/aat/resources/features/F-126/F126_Update_Case_With_On_Behalf_Of_User.td.json
  src/aat/resources/features/F-126/S-1261.td.json
  src/aat/resources/features/common/case/befta-jurisdiction2-case-creation_by_solicitor_1/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Case_Update_Solicitor_1.td.json
  src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventEntity.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventMapper.java
  src/main/java/uk/gov/hmcts/ccd/data/user/CachedUserRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepository.java
  src/main/java/uk/gov/hmcts/ccd/data/user/UserRepository.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/aggregated/CaseViewEvent.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/std/AuditEvent.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/std/CaseDataContent.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventService.java
  src/main/java/uk/gov/hmcts/ccd/v2/external/controller/CaseController.java
  src/main/resources/db/changelog/db.changelog-RDM-10165.xml
  src/main/resources/db/changelog/db.changelog-master.xml
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventMapperTest.java
  src/test/java/uk/gov/hmcts/ccd/data/user/DefaultUserRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventDefinitionServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/DefaultCreateEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/CaseControllerTestIT.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1225

#1256 RDM-10294 Fix All Recent CVEs in All CCD Apps
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1256

#1219 RDM-10141 Remediate API Calls Running Expensive Select Queries on DB
  Jenkinsfile_CNP
  charts/ccd-data-store-api/values.preview.template.yaml
  src/main/resources/db/changelog/db.changelog-RDM-10141-1.xml
  src/main/resources/db/changelog/db.changelog-RDM-10141-2.xml
  src/main/resources/db/changelog/db.changelog-RDM-10141-3.xml
  src/main/resources/db/changelog/db.changelog-RDM-10340.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1219

#1265 change data store develop pr
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1265

#1262 RDM-10519 [3rd Round] Create Indexes on DB to Remediate Expensive Que…
  src/main/resources/db/changelog/db.changelog-RDM-10519.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1262

#1280 changed app-insights Logging threshold to info (default warn)
  lib/AI-Agent.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1280

#1251 RDM-10167: Build new MessageQueueCandidates database structure
  src/main/resources/db/changelog/db.changelog-RDM-10167.xml
  src/main/resources/db/changelog/db.changelog-master.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1251

#1273 RDM-10549 Fix 2 CVEs Newly Reported on All 4 Java Apps
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1273

#1238 Aca 112 - bump befta-fw to 6.2.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1238

#1272 RDM-10527 - Eager fetch SignificantItems to reduce number of DB calls
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseAuditEventEntity.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1272

#1279 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1279

#1285 patch concurrent execution of functional tests
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1285

#1222 RDM-10154 : Fix temporarily disabled tests.
  dependency-check-suppressions.xml
  src/aat/resources/features/F-109/F-109.feature
  src/aat/resources/features/F-120 supplementary_data in ES Search API/F-120.feature
  src/aat/resources/features/F-121/F-121.feature
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1222
