Repository hmcts/ccd-data-store-api, pull requests merged in 2021-04, with the labels that each got.

#1430 RDM-9182: Handle SQL exceptions and remove sql grammar from errors
  src/main/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandler.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandlerTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1430

#1434 Revert "temporarily disable failing tests"
  src/aat/resources/features/F-127 - Even Enabling Condition/F-127.feature
  src/aat/resources/features/F-128 - Dynamic Lists/F-128.feature
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1434

#1416 Create dummy.yml
  .github/workflows/dummy.yml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1416

#1446 Fix functional tests on case reference
  src/aat/resources/features/F-104/Base_Case_Fields_Expected.td.json
  src/aat/resources/features/F-109/S-945.td.json
  src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.3.td.json
  src/aat/resources/features/F-120 supplementary_data in ES Search API/S-120.4.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1446

#1255 Ta 82 ccd provider pact test
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/CasesControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestCaseDefinitionRepository.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestCreateCaseOperation.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestCreateEventOperation.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestGetCaseOperation.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestSecurityUtils.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestStartEventOperation.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestSubmitCaseTransaction.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/SecurityMockConfiguration.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/caseassigned/CaseAssignedUserRolesProviderTest.java
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/caseassigned/CaseAssignedUserRolesProviderTestContext.java
  src/contractTest/resources/application.properties
  src/main/java/uk/gov/hmcts/ccd/data/SecurityUtils.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/query/UserAuthorisationSecurity.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransaction.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpoint.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1255

#1449 TA-82: Disable pact tests
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1449

#1453 Rdm 11956
  README.md
  charts/ccd-data-store-api/Chart.yaml
  charts/ccd-data-store-api/values.yaml
  dependency-check-suppressions.xml
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/CasesControllerProviderTest.java
  src/contractTest/resources/application.properties
  src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
  src/main/java/uk/gov/hmcts/ccd/domain/types/DocumentValidator.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ccd/domain/types/DocumentValidatorTest.java
  src/test/resources/test.properties
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1453

#1460 RDM-12175 Updated chart version
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1460

#1456 RDM-12143 CVE-2021-29425 - bump up dependencies to resolve CVE
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1456

#1431 RDM-9354 Case Sensitive CaseRole on Add Case-Assigned Users and Roles endpoint
  src/main/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperation.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/caseaccess/CaseAccessOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/external/controller/AddCaseAssignedUserRolesControllerIT.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1431

#1439 Rdm 11603 - fit in github credentials for workflow
  .github/workflows/publish-swagger-specs.yml
  .github/workflows/scheduled-dummy-commit.yml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1439

#1462 Delete dummy.yml
  .github/workflows/dummy.yml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1462

#1459 Rdm 11126
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchQueryHelper.java
  src/main/java/uk/gov/hmcts/ccd/endpoint/std/CaseSearchEndpoint.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/ElasticsearchQueryHelperTest.java
  src/test/java/uk/gov/hmcts/ccd/v2/internal/controller/UICaseSearchControllerIT.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1459
