Repository hmcts/ccd-data-store-api, pull requests merged in 2022-09, with the labels that each got.

#2080 CCD-3630 - Take access profiles into account with Global Search post-filtering
  src/main/java/uk/gov/hmcts/ccd/domain/service/globalsearch/GlobalSearchParser.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/mapper/CaseDetailsMapper.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/globalsearch/GlobalSearchParserTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2080

#2085 Suppress CVE-2022-25857 in suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2085

#2083 CCD-3656 adjust GS baseLocation lookup mapping
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/S-1005.1.td.json
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/S-1005.2.td.json
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/S-1005.6.td.json
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/S-1005.7.td.json
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/S-1005.8.td.json
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/S-1005.9.td.json
  src/aat/resources/features/common/casefields/CaseManagementLocation_FromRefData_SiblingContext.td.json
  src/main/java/uk/gov/hmcts/ccd/domain/model/refdata/LocationLookup.java
  src/test/java/uk/gov/hmcts/ccd/TestFixtures.java
  src/test/java/uk/gov/hmcts/ccd/data/ReferenceDataRepositoryIT.java
  src/test/java/uk/gov/hmcts/ccd/data/ReferenceDataRepositoryTest.java
  src/test/java/uk/gov/hmcts/ccd/data/ReferenceDataTestFixtures.java
  src/test/resources/tests/refdata/get_building_locations.json
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2083

#2082 Ccd 3577 cleanup CVE suppressions
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2082

#2094 Revert "CCD-3436 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed"
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2094

#2091 Revert "CCD-3539-CCD-3574: Update Jenkinsfile_nightly (Stop running Nightly builds on weekends, remove FTs)"
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2091

#2097 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2097

#2065 CCD-3509 CVE-2021-22044 suppression removed
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/uk/gov/hmcts/ccd/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/UIDService.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ccd/RestTemplateConfigurationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentAmApiClientTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/exceptions/RestExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/ccd/security/idam/IdamRepositoryTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2065

#2067 CCD-3152 Functional tests
  build.gradle
  src/aat/resources/features/F-069 - Event Enabling Condition/F-069.feature
  src/aat/resources/features/F-069 - Event Enabling Condition/F-069_CaseCreation.td.json
  src/aat/resources/features/F-069 - Event Enabling Condition/F-069_CreateCaseTokenCreation.td.json
  src/aat/resources/features/F-069 - Event Enabling Condition/F-069_Test_Data_Base.td.json
  src/aat/resources/features/F-069 - Event Enabling Condition/S-069.1.td.json
  src/aat/resources/features/F-069 - Event Enabling Condition/S-069.2.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2067

#2107 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2107

#2111 CCD-3736: Suppress CVE-2022-38752
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2111

#2076 created ExceptionHandlingFilter in Security Filter chain
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/ccd/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/security/filters/ExceptionHandlingFilter.java
  src/test/java/uk/gov/hmcts/ccd/security/filters/ExceptionHandlingFilterTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2076
