Repository hmcts/ccd-data-store-api, pull requests merged in 2022-11, with the labels that each got.

#2134 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2134

#2126 CCD-3733 Update test definitions version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2126

#2145 CCD-3918 CVE-2022-42252
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2145

#2146 CCD-3917 Spring Security Upgrade
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2146

#2151 Ccd 3839 swagger same class names
  src/main/java/uk/gov/hmcts/ccd/domain/model/casefileview/Document.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2151

#2155 CCD-4010: Issue on event_token reported by fortify
  src/aat/resources/features/F-037 - Submit Event V2 External/F-037_Test_Data_Base.td.json
  src/aat/resources/features/F-044 - Submit Event V1 External/F-044_Test_Data_Base.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2155

#2071 CCD-3533 auto create new suppression for cve
  .github/workflows/dependency-check.yml
  build.gradle
  gradle/suppress.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2071

#2029 CCD-3396: Improve Logging
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlService.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceImpl.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/AuthorisedCreateEventOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/types/CaseDataValidator.java
  src/test/java/uk/gov/hmcts/ccd/TestConfiguration.java
  src/test/java/uk/gov/hmcts/ccd/data/definition/DefaultCaseDefinitionRepositoryIT.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/TestBuildersUtil.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/AuthorisedCreateEventOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/types/CaseDataValidatorTest.java
  src/test/resources/tests/CaseDataValidator_CaseField.json
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2029

#2149 CCD-3781: Add Gradle tasks runRemoteAAT and reloadEnvSecretsAAT to Data Store.
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2149

#2148 CCD-3734 Update test definitions version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2148

#2159 CCD-3916 Update Github actions in workflow
  .github/workflows/publish-swagger-specs.yml
  .github/workflows/scheduled-dummy-commit.yml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2159
