Repository hmcts/ccd-data-store-api, pull requests merged in 2022-01, with the labels that each got.

#1706 LAU-127: Initial commit of LAU auditing
  charts/ccd-data-store-api/Chart.yaml
  charts/ccd-data-store-api/values.yaml
  src/contractTest/resources/application.properties
  src/main/java/uk/gov/hmcts/ccd/AuditCaseRemoteConfiguration.java
  src/main/java/uk/gov/hmcts/ccd/auditlog/AuditService.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/lau/ActionLog.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/lau/CaseActionPostRequest.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/lau/CaseSearchPostRequest.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/lau/SearchLog.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/lau/AuditCaseRemoteOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/lau/AuditRemoteOperation.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ccd/AuditCaseRemoteConfigurationTest.java
  src/test/java/uk/gov/hmcts/ccd/auditlog/AuditServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/model/lau/CaseActionPostRequestTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/model/lau/CaseSearchPostRequestTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/lau/AuditCaseRemoteOperationIT.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/lau/AuditCaseRemoteOperationTest.java
  src/test/resources/test.properties
Labels: ** DO NOT MERGE **, ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1706

#1737 RDM-12961: supplementary
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F-130-Prerequisite.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F-130.feature
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F-130_Test_Data_Base.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F-130_Update_Supplementary_Data_Base.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F130_Case_Data_Create.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F130_Case_Data_Create_C1.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F130_Case_Data_Create_C1_Token_Creation.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/F130_Case_Data_Create_Token_Creation.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/S-1269.td.json
  src/aat/resources/features/F-130 - Create Case Citizen V1 Supplementary Data/S-1270.td.json
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestCreateCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/SetSupplementaryDataQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/std/CaseDataContent.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/AuthorisedCreateCaseOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/DefaultCreateCaseOperation.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/supplementarydata/SetSupplementaryDataQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/DefaultCreateCaseOperationTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1737

#1788 RDM-12677 ccd-test-definitions pre-release
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1788

#1787 RDM-13070 Remove caching of jurisdictions in Global Search
  src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1787

#1786 RDM-13073 Adjust Reference Data Cache schedule
  src/contractTest/resources/application.properties
  src/main/java/uk/gov/hmcts/ccd/data/ReferenceDataRepository.java
  src/main/resources/application.properties
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1786

#1789 CCD-2400: Reschedule nightly build
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1789

#1793 Ccd 2455
  Jenkinsfile_CNP
  build.gradle
  charts/ccd-data-store-api/values.preview.template.yaml
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/F-1005.feature
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1793

#1625 CCD-913: Add request level caching for jurisdiction cache
  src/main/java/uk/gov/hmcts/ccd/data/definition/CachedCaseDefinitionRepository.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackInvokerWireMockTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CaseDetailsEndpointUserRolesIT.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1625

#1779 RDM-13063 - Support WaysToPay as field with no value
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/FieldTypeDefinition.java
  src/test/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetailsTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1779

#1782 RDM-13012 Create database Index for new column - CaseAccessCategory
  src/main/resources/db/migration/V20220111_13012__RDM-13012_new_index_for_case_access_category.sql
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1782

#1784 RDM-12977 Establish the new FlagLauncher base type
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetails.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/definition/FieldTypeDefinition.java
  src/test/java/uk/gov/hmcts/ccd/domain/model/definition/CaseDetailsTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1784

#1792 Amending suppression dates by 1 month
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1792

#1757 CCD 2273: Useful SQL queries for Data Store DB
  repository/src/main/resources/db/useful-queries/Useful select queries.sql
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1757

#1806 CCD-2465: Temporarily disable F-1005 tests
  src/aat/resources/features/F-1005 - GlobalSearch - Search cases/F-1005.feature
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1806

#1776 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1776

#1807 CCD-2457: PACT tests failing against CCD consumer
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1807

#1823 [Merge only after 11pm!!] downscale DB back to level before
  infrastructure/prod.tfvars
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-1823
