Repository hmcts/ccd-data-store-api, pull requests merged in 2023-05, with the labels that each got.

#2249 CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2249

#2261 ST-1357 Add S2S for Special Tribunals Case API
  charts/ccd-data-store-api/Chart.yaml
  charts/ccd-data-store-api/values.yaml
  src/main/resources/application.properties
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2261

#2266 CCD-4687 Update renovate.json
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2266
