Repository hmcts/ccd-data-store-api, pull requests merged in 2023-04, with the labels that each got.

#2252 CCD-4457 Include custom Document types
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/SimpleCaseTypeMetadataExtractor.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/AbstractBaseCaseFieldMetadataExtractorTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/SimpleCaseTypeMetadataExtractorTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2252

#2257 Update Chart.yaml
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2257

#2258 CCD-4599 : Update build.gradle
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2258
