Repository hmcts/ccd-data-store-api, pull requests merged in 2024-03, with the labels that each got.

#2348 CCD-4969: bumped spring-security.version to v5.7.10
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2348

#2372 Setting storage auto growth to true in aat and prod
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, no-changes, rel:ccd-data-store-api-pr-2372

#2363 Bumped versions but still pulling in old version
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2363

#2333 Ga 13 filter by case access group
  src/main/java/uk/gov/hmcts/ccd/data/casedataaccesscontrol/RoleAssignmentAttributesResource.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/RoleAssignmentAttributes.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/MatcherType.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/RoleAttributeMatcher.java
  src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcherTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/accessprofile/filter/BaseFilter.java
Labels: ** DO NOT MERGE **, ns:ccd, prd:ccd, add-or-update, rel:ccd-data-store-api-pr-2333

#2375 GA-13 Update ccd-test-definitions version to match the version in ccd…
  build.gradle
Labels: ** DO NOT MERGE **, ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-data-store-api-pr-2375

#2377 GA-13 Update beftaFwVersion version to match the version in ccd-defin…
  build.gradle
Labels: ** DO NOT MERGE **, ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-data-store-api-pr-2377

#2251 Ccd 4412 deprecated usage internal urls
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-data-store-api-pr-2251

#2374 CCD-5180 flexible server database fix perms
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, no-changes, rel:ccd-data-store-api-pr-2374

#2378 Update main.tf
  infrastructure/main.tf
Labels: ns:ccd, prd:ccd, no-changes, rel:ccd-data-store-api-pr-2378

#2334 Ga 14 search by case group access
  src/aat/resources/features/F-035 - Get Case V2 External/F-035.feature
  src/aat/resources/features/F-035 - Get Case V2 External/S-960.td.json
  src/aat/resources/features/F-108 - External Search API/F-108.feature
  src/aat/resources/features/F-108 - External Search API/S-948.td.json
  src/aat/resources/features/common/case/GroupAccess_Full_Case_Creation_Data.td.json
  src/aat/resources/features/common/case/GroupAccess_Full_Case_Creation_Data_Token_Creation.td.json
  src/aat/resources/features/common/users/GroupAccessCaseworkerAutotest.td.json
  src/contractTest/resources/application.properties
  src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/CaseDetailsEntity.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/BasicGrantTypeQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/ChallengedGrantTypeQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/ExcludedGrantTypeQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeSqlQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/SpecificGrantTypeQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/StandardGrantTypeQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcher.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/SearchRoleAssignment.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/BasicGrantTypeESQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ChallengedGrantTypeESQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ExcludedGrantTypeESQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/GrantTypeESQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/SpecificGrantTypeESQueryBuilder.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/StandardGrantTypeESQueryBuilder.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V20231120_0000__GA-14_new_index_for_case_access_groups.sql
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/AccessControlGrantTypeQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/BasicGrantTypeQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/ChallengedGrantTypeQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/data/casedetails/search/builder/GrantTypeQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/model/casedataaccesscontrol/matcher/CaseAccessGroupsMatcherTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/casedataaccesscontrol/RoleAssignmentsMapperTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/AccessControlGrantTypeESQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/BasicGrantTypeESQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ChallengedGrantTypeESQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/ExcludedGrantTypeESQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/GrantTypeESQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/SpecificGrantTypeESQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/search/elasticsearch/builder/StandardGrantTypeESQueryBuilderTest.java
  src/test/java/uk/gov/hmcts/ccd/test/RoleAssignmentsHelper.java
Labels: ** DO NOT MERGE **, ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-data-store-api-pr-2334, ccd-data-store-api-pr-2334-es-master

#2373 Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 9.0.82
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2373

#2386 CSFD-97 [Case Create/Update] Populate Document's "upload_timestamp" Value - Feature Toggle
  src/contractTest/resources/application.properties
  src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentTimestampService.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/getcasedocument/CaseDocumentTimestampServiceTest.java
Labels: ns:ccd, prd:ccd, enable_keep_helm, rel:ccd-data-store-api-pr-2386

#2383 CIV-13093 log error fields
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/AccessControlServiceImpl.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2383

#2389 GA-28 refactoring
  README.md
  build.gradle
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/F-1023.feature
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/F-1023_CreateCasePreRequisiteCaseworkerBase.td.json
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/F-1023_CreateCasePreRequisiteCaseworker_noCaseAccessGroup.td.json
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/S-1023.1.td.json
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/S-1023.2.td.json
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/S-1023.3.td.json
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/S-1023.4.td.json
  src/aat/resources/features/F-1023 - Case update with caseAccessGroups/S-1023.5.td.json
  src/contractTest/java/uk/gov/hmcts/ccd/v2/external/controller/ContractTestSubmitCaseTransaction.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessGroupUtils.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransaction.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventService.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/accessprofile/filter/BaseFilter.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/accessprofile/filter/RoleAssignmentsFilteringServiceImplTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/CaseAccessGroupUtilsTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransactionCaseAccessGroupTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createcase/SubmitCaseTransactionTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/createevent/CreateCaseEventServiceTest.java
Labels: ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-data-store-api-pr-2389
