Repository hmcts/ccd-data-store-api, pull requests merged in 2024-06, with the labels that each got.

#2427 CCD-5232 Update-ithc main.tf Decomission v11 Postgres database
  build.gradle
  dependency-check-suppressions.xml
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:ccd, prd:ccd, aat/destroy, prod/destroy, rel:ccd-data-store-api-pr-2427, ithc/destroy

#2429 merge ithc into master
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:ccd, prd:ccd, aat/destroy, prod/destroy, rel:ccd-data-store-api-pr-2429

#2423 CCD-5480 Fix Document validation error - upload_timestamp regex
  src/main/java/uk/gov/hmcts/ccd/domain/types/DocumentValidator.java
  src/test/java/uk/gov/hmcts/ccd/domain/types/DateTimeValidatorTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2423

#2436 Ccd 4775 modify db trigger insert update
  src/main/resources/db/migration/V20240617_4775__CCD-4775_modify_db_trigger_for_IU.sql
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2436

#2408 implement filterCaseTabFieldsByReadAccess to CaseHistoryView
  charts/ccd-data-store-api/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AbstractAuthorisedCaseViewOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseHistoryViewOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseViewOperation.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCaseHistoryViewOperationTest.java
Labels: ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-data-store-api-pr-2408

#2442 Update F-1022_SearchCaseBase.td.json
  src/aat/resources/features/F-1022 - CaseAccessGroups Complex Type/F-1022_SearchCaseBase.td.json
Labels: ns:ccd, prd:ccd, enable_keep_helm, enable_keep_help, rel:ccd-data-store-api-pr-2442

#2440 Chore Update demo.tfvars increase demo db storage
  infrastructure/demo.tfvars
Labels: ns:ccd, prd:ccd, aat/no-changes, prod/no-changes, rel:ccd-data-store-api-pr-2440
