Repository hmcts/ccd-data-store-api, pull requests merged in 2024-05, with the labels that each got.

#2413 Reference to the ft timeout extension branch
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2413

#2416 Fix for failing FT in pipeline build
  src/aat/resources/features/F-1006 - GlobalSearch - AC tests/F-1006_SearchCaseBaseRestricted.td.json
  src/aat/resources/features/F-1006 - GlobalSearch - AC tests/S-1006.2.td.json
Labels: ** DO NOT MERGE **, ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2416

#2418 CCD-5232 Update values.yaml to flexible server
  charts/ccd-data-store-api/Chart.yaml
  charts/ccd-data-store-api/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2418

#2420 CCD-5232 Update prod.tfvars scale down v11 D/B
  infrastructure/prod.tfvars
Labels: ns:ccd, prd:ccd, aat/no-changes, prod/add-or-update, rel:ccd-data-store-api-pr-2420

#2380 CCD-5201 CVE fixes.
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2380
