Repository hmcts/ccd-data-store-api, pull requests merged in 2024-12, with the labels that each got.

#2507 CME-109 to use ccd-test-definition version 7.24.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2507

#2510 Fix FT-109 ordering failure and bump version for befta-fw from 9.0.2 …
  build.gradle
  src/aat/resources/features/F-109 - caseworker-caa Authorisation/S-945.td.json
  src/aat/resources/features/F-109 - caseworker-caa Authorisation/S-946.td.json
Labels: ns:ccd, prd:ccd, keep-helm, enable_keep_helm, ns:ccd prd:ccd, ccd-data-store-api-pr-2510, rel:ccd-data-store-api-pr-2510, ccd-data-store-api-pr-2510-es-master

#2463 CCD-5159:
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, aat/destroy, prod/destroy, rel:ccd-data-store-api-pr-2463
