Repository hmcts/ccd-data-store-api, pull requests merged in 2025-07, with the labels that each got.

#2603 Chore fix reporting perms
  infrastructure/main.tf
Labels: ** DO NOT MERGE **, ns:ccd, prd:ccd, aat/no-changes, prod/destroy, rel:ccd-data-store-api-pr-2603

#2608 CCD-6601 :: Update dependency-check-suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2608

#2604 Add feature flag to control case-doc-am-api usage in DocumentSanitiser
  src/main/java/uk/gov/hmcts/ccd/ApplicationParams.java
  src/main/java/uk/gov/hmcts/ccd/domain/types/sanitiser/DocumentSanitiser.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/ccd/domain/types/sanitiser/DocumentSanitiserTest.java
  src/test/resources/mappings/dm-documents.json
  src/test/resources/test.properties
Labels: ns:ccd, prd:ccd, aat/no-changes, prod/destroy, rel:ccd-data-store-api-pr-2604

#2588 Ccd 6378 remove field level data classification
  src/aat/resources/features/F-108 - External Search API/S-912/S-912.td.json
  src/aat/resources/features/F-129 - Access Control SC/F-129.feature
  src/aat/resources/features/F-129 - Access Control SC/S-129.1.td.json
  src/aat/resources/features/F-129 - Access Control SC/S-129.2.td.json
  src/aat/resources/features/F-129 - Access Control SC/S-129.3.td.json
  src/aat/resources/features/F-129 - Access Control SC/S-129.4.td.json
  src/aat/resources/features/F-129 - Access Control SC/S-129.5.td.json
  src/aat/resources/features/F-129 - Access Control SC/SC_Public_Case_Created.td.json
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/AuthorisedGetCriteriaOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/aggregated/ClassifiedGetCriteriaOperation.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationService.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceImpl.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/globalsearch/GlobalSearchParser.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchResultViewGenerator.java
  src/main/java/uk/gov/hmcts/ccd/domain/service/search/CaseSearchesViewAccessControl.java
  src/test/java/uk/gov/hmcts/ccd/ElasticsearchIT.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/CaseSearchResultViewGeneratorTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/CaseSearchesViewAccessControlTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/aggregated/ClassifiedGetCriteriaOperationTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/common/SecurityClassificationServiceTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/globalsearch/GlobalSearchParserTest.java
  src/test/java/uk/gov/hmcts/ccd/endpoint/std/CallbackTest.java
  src/test/resources/sql/insert_cases_get_case_links.sql
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2588

#2550 new Azure vault for token secret
  charts/ccd-data-store-api/Chart.yaml
  charts/ccd-data-store-api/values.aat.template.yaml
  charts/ccd-data-store-api/values.preview.template.yaml
  charts/ccd-data-store-api/values.yaml
Labels: ns:ccd, prd:ccd, keep-helm, enable_keep_helm, rel:ccd-data-store-api-pr-2550

#2611 CME-732: Update beftaFwVersion to 9.2.4 in build.gradle
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2611

#2627 CCD-6640 :: Multiple CVE Suppressions
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2627

#2626 CCD 6636 :: Fix CVE
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2626
