Repository hmcts/ccd-data-store-api, pull requests merged in 2025-05, with the labels that each got.

#2566 CME-289: Suppress pact tests to unblock ccd-data store
  Jenkinsfile_CNP
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2566

#2575 Update dependency-check-suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2575

#2564 Fix flakey tests
  src/test/java/uk/gov/hmcts/ccd/ElasticsearchITSetup.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackInvokerWireMockTest.java
  src/test/java/uk/gov/hmcts/ccd/domain/service/stdapi/DocumentsOperationTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-data-store-api-pr-2564
